//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 08:24:40 AM IST 
//


package com.airforecast.model.weather;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="current_weather">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="temp" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="temp_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="wind">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="pressure" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="weather_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="weather_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="forecast" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="temp_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="day_max_temp" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="night_min_temp" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="day">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="weather_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="weather_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="wind">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="dir_degree" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="precip_mm" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="cloudcover" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="visibility_km" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="night">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="weather_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="weather_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="wind">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="dir_degree" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="precip_mm" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="cloudcover" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="visibility_km" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "currentWeather",
    "forecast"
})
@XmlRootElement(name = "weather")
public class Weather {

	
    @XmlElement(name = "curren_weather", required = true)
    protected Weather.CurrentWeather currentWeather;
    protected List<Weather.Forecast> forecast;


	/**
     * Gets the value of the currentWeather property.
     * 
     * @return
     *     possible object is
     *     {@link Weather.CurrentWeather }
     *     
     */
    public Weather.CurrentWeather getCurrentWeather() {
        return currentWeather;
    }

    /**
     * Sets the value of the currentWeather property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weather.CurrentWeather }
     *     
     */
    public void setCurrentWeather(Weather.CurrentWeather value) {
        this.currentWeather = value;
    }

    /**
     * Gets the value of the forecast property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forecast property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForecast().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Weather.Forecast }
     * 
     * 
     */
    public List<Weather.Forecast> getForecast() {
        if (forecast == null) {
            forecast = new ArrayList<Weather.Forecast>();
        }
        return this.forecast;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="temp" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="temp_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="wind">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="pressure" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="weather_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weather_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "temp",
        "tempUnit",
        "wind",
        "humidity",
        "pressure",
        "weatherText",
        "weatherCode"
    })
    public static class CurrentWeather {

        protected byte temp;
        @XmlElement(name = "temp_unit", required = true)
        protected String tempUnit;
        @XmlElement(required = true)
        protected Weather.CurrentWeather.Wind wind;
        protected byte humidity;
        protected short pressure;
        @XmlElement(name = "weather_text", required = true)
        protected String weatherText;
        @XmlElement(name = "weather_code")
        protected byte weatherCode;

        /**
         * Gets the value of the temp property.
         * 
         */
        public byte getTemp() {
            return temp;
        }

        /**
         * Sets the value of the temp property.
         * 
         */
        public void setTemp(byte value) {
            this.temp = value;
        }

        /**
         * Gets the value of the tempUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTempUnit() {
            return tempUnit;
        }

        /**
         * Sets the value of the tempUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTempUnit(String value) {
            this.tempUnit = value;
        }

        /**
         * Gets the value of the wind property.
         * 
         * @return
         *     possible object is
         *     {@link Weather.CurrentWeather.Wind }
         *     
         */
        public Weather.CurrentWeather.Wind getWind() {
            return wind;
        }

        /**
         * Sets the value of the wind property.
         * 
         * @param value
         *     allowed object is
         *     {@link Weather.CurrentWeather.Wind }
         *     
         */
        public void setWind(Weather.CurrentWeather.Wind value) {
            this.wind = value;
        }

        /**
         * Gets the value of the humidity property.
         * 
         */
        public byte getHumidity() {
            return humidity;
        }

        /**
         * Sets the value of the humidity property.
         * 
         */
        public void setHumidity(byte value) {
            this.humidity = value;
        }

        /**
         * Gets the value of the pressure property.
         * 
         */
        public short getPressure() {
            return pressure;
        }

        /**
         * Sets the value of the pressure property.
         * 
         */
        public void setPressure(short value) {
            this.pressure = value;
        }

        /**
         * Gets the value of the weatherText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWeatherText() {
            return weatherText;
        }

        /**
         * Sets the value of the weatherText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWeatherText(String value) {
            this.weatherText = value;
        }

        /**
         * Gets the value of the weatherCode property.
         * 
         */
        public byte getWeatherCode() {
            return weatherCode;
        }

        /**
         * Sets the value of the weatherCode property.
         * 
         */
        public void setWeatherCode(byte value) {
            this.weatherCode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "speed",
            "dir",
            "windUnit"
        })
        public static class Wind {

            protected byte speed;
            @XmlElement(required = true)
            protected String dir;
            @XmlElement(name = "wind_unit", required = true)
            protected String windUnit;

            /**
             * Gets the value of the speed property.
             * 
             */
            public byte getSpeed() {
                return speed;
            }

            /**
             * Sets the value of the speed property.
             * 
             */
            public void setSpeed(byte value) {
                this.speed = value;
            }

            /**
             * Gets the value of the dir property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDir() {
                return dir;
            }

            /**
             * Sets the value of the dir property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDir(String value) {
                this.dir = value;
            }

            /**
             * Gets the value of the windUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWindUnit() {
                return windUnit;
            }

            /**
             * Sets the value of the windUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWindUnit(String value) {
                this.windUnit = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="temp_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="day_max_temp" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="night_min_temp" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="day">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="weather_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="weather_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="wind">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="dir_degree" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="precip_mm" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="cloudcover" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="visibility_km" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="night">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="weather_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="weather_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="wind">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="dir_degree" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="precip_mm" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="cloudcover" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="visibility_km" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "tempUnit",
        "dayMaxTemp",
        "nightMinTemp",
        "day",
        "night"
    })
    public static class Forecast {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "temp_unit", required = true)
        protected String tempUnit;
        @XmlElement(name = "day_max_temp")
        protected byte dayMaxTemp;
        @XmlElement(name = "night_min_temp")
        protected byte nightMinTemp;
        @XmlElement(required = true)
        protected Weather.Forecast.Day day;
        @XmlElement(required = true)
        protected Weather.Forecast.Night night;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the tempUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTempUnit() {
            return tempUnit;
        }

        /**
         * Sets the value of the tempUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTempUnit(String value) {
            this.tempUnit = value;
        }

        /**
         * Gets the value of the dayMaxTemp property.
         * 
         */
        public byte getDayMaxTemp() {
            return dayMaxTemp;
        }

        /**
         * Sets the value of the dayMaxTemp property.
         * 
         */
        public void setDayMaxTemp(byte value) {
            this.dayMaxTemp = value;
        }

        /**
         * Gets the value of the nightMinTemp property.
         * 
         */
        public byte getNightMinTemp() {
            return nightMinTemp;
        }

        /**
         * Sets the value of the nightMinTemp property.
         * 
         */
        public void setNightMinTemp(byte value) {
            this.nightMinTemp = value;
        }

        /**
         * Gets the value of the day property.
         * 
         * @return
         *     possible object is
         *     {@link Weather.Forecast.Day }
         *     
         */
        public Weather.Forecast.Day getDay() {
            return day;
        }

        /**
         * Sets the value of the day property.
         * 
         * @param value
         *     allowed object is
         *     {@link Weather.Forecast.Day }
         *     
         */
        public void setDay(Weather.Forecast.Day value) {
            this.day = value;
        }

        /**
         * Gets the value of the night property.
         * 
         * @return
         *     possible object is
         *     {@link Weather.Forecast.Night }
         *     
         */
        public Weather.Forecast.Night getNight() {
            return night;
        }

        /**
         * Sets the value of the night property.
         * 
         * @param value
         *     allowed object is
         *     {@link Weather.Forecast.Night }
         *     
         */
        public void setNight(Weather.Forecast.Night value) {
            this.night = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="weather_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="weather_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="wind">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="dir_degree" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="precip_mm" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="cloudcover" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="visibility_km" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "weatherText",
            "weatherCode",
            "wind",
            "precipMm",
            "cloudcover",
            "humidity",
            "visibilityKm",
            "pressureMb"
        })
        public static class Day {

            @XmlElement(name = "weather_text", required = true)
            protected String weatherText;
            @XmlElement(name = "weather_code")
            protected byte weatherCode;
            @XmlElement(required = true)
            protected Weather.Forecast.Day.Wind wind;
            @XmlElement(name = "precip_mm")
            protected float precipMm;
            protected byte cloudcover;
            protected byte humidity;
            @XmlElement(name = "visibility_km")
            protected byte visibilityKm;
            @XmlElement(name = "pressure_mb")
            protected short pressureMb;

            /**
             * Gets the value of the weatherText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWeatherText() {
                return weatherText;
            }

            /**
             * Sets the value of the weatherText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWeatherText(String value) {
                this.weatherText = value;
            }

            /**
             * Gets the value of the weatherCode property.
             * 
             */
            public byte getWeatherCode() {
                return weatherCode;
            }

            /**
             * Sets the value of the weatherCode property.
             * 
             */
            public void setWeatherCode(byte value) {
                this.weatherCode = value;
            }

            /**
             * Gets the value of the wind property.
             * 
             * @return
             *     possible object is
             *     {@link Weather.Forecast.Day.Wind }
             *     
             */
            public Weather.Forecast.Day.Wind getWind() {
                return wind;
            }

            /**
             * Sets the value of the wind property.
             * 
             * @param value
             *     allowed object is
             *     {@link Weather.Forecast.Day.Wind }
             *     
             */
            public void setWind(Weather.Forecast.Day.Wind value) {
                this.wind = value;
            }

            /**
             * Gets the value of the precipMm property.
             * 
             */
            public float getPrecipMm() {
                return precipMm;
            }

            /**
             * Sets the value of the precipMm property.
             * 
             */
            public void setPrecipMm(float value) {
                this.precipMm = value;
            }

            /**
             * Gets the value of the cloudcover property.
             * 
             */
            public byte getCloudcover() {
                return cloudcover;
            }

            /**
             * Sets the value of the cloudcover property.
             * 
             */
            public void setCloudcover(byte value) {
                this.cloudcover = value;
            }

            /**
             * Gets the value of the humidity property.
             * 
             */
            public byte getHumidity() {
                return humidity;
            }

            /**
             * Sets the value of the humidity property.
             * 
             */
            public void setHumidity(byte value) {
                this.humidity = value;
            }

            /**
             * Gets the value of the visibilityKm property.
             * 
             */
            public byte getVisibilityKm() {
                return visibilityKm;
            }

            /**
             * Sets the value of the visibilityKm property.
             * 
             */
            public void setVisibilityKm(byte value) {
                this.visibilityKm = value;
            }

            /**
             * Gets the value of the pressureMb property.
             * 
             */
            public short getPressureMb() {
                return pressureMb;
            }

            /**
             * Sets the value of the pressureMb property.
             * 
             */
            public void setPressureMb(short value) {
                this.pressureMb = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="dir_degree" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "speed",
                "dir",
                "dirDegree",
                "windUnit"
            })
            public static class Wind {

                protected byte speed;
                @XmlElement(required = true)
                protected String dir;
                @XmlElement(name = "dir_degree")
                protected byte dirDegree;
                @XmlElement(name = "wind_unit", required = true)
                protected String windUnit;

                /**
                 * Gets the value of the speed property.
                 * 
                 */
                public byte getSpeed() {
                    return speed;
                }

                /**
                 * Sets the value of the speed property.
                 * 
                 */
                public void setSpeed(byte value) {
                    this.speed = value;
                }

                /**
                 * Gets the value of the dir property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDir() {
                    return dir;
                }

                /**
                 * Sets the value of the dir property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDir(String value) {
                    this.dir = value;
                }

                /**
                 * Gets the value of the dirDegree property.
                 * 
                 */
                public byte getDirDegree() {
                    return dirDegree;
                }

                /**
                 * Sets the value of the dirDegree property.
                 * 
                 */
                public void setDirDegree(byte value) {
                    this.dirDegree = value;
                }

                /**
                 * Gets the value of the windUnit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWindUnit() {
                    return windUnit;
                }

                /**
                 * Sets the value of the windUnit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWindUnit(String value) {
                    this.windUnit = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="weather_text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="weather_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="wind">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="dir_degree" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="precip_mm" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="cloudcover" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="humidity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="visibility_km" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="pressure_mb" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "weatherText",
            "weatherCode",
            "wind",
            "precipMm",
            "cloudcover",
            "humidity",
            "visibilityKm",
            "pressureMb"
        })
        public static class Night {

            @XmlElement(name = "weather_text", required = true)
            protected String weatherText;
            @XmlElement(name = "weather_code")
            protected byte weatherCode;
            @XmlElement(required = true)
            protected Weather.Forecast.Night.Wind wind;
            @XmlElement(name = "precip_mm")
            protected float precipMm;
            protected byte cloudcover;
            protected byte humidity;
            @XmlElement(name = "visibility_km")
            protected byte visibilityKm;
            @XmlElement(name = "pressure_mb")
            protected short pressureMb;

            /**
             * Gets the value of the weatherText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWeatherText() {
                return weatherText;
            }

            /**
             * Sets the value of the weatherText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWeatherText(String value) {
                this.weatherText = value;
            }

            /**
             * Gets the value of the weatherCode property.
             * 
             */
            public byte getWeatherCode() {
                return weatherCode;
            }

            /**
             * Sets the value of the weatherCode property.
             * 
             */
            public void setWeatherCode(byte value) {
                this.weatherCode = value;
            }

            /**
             * Gets the value of the wind property.
             * 
             * @return
             *     possible object is
             *     {@link Weather.Forecast.Night.Wind }
             *     
             */
            public Weather.Forecast.Night.Wind getWind() {
                return wind;
            }

            /**
             * Sets the value of the wind property.
             * 
             * @param value
             *     allowed object is
             *     {@link Weather.Forecast.Night.Wind }
             *     
             */
            public void setWind(Weather.Forecast.Night.Wind value) {
                this.wind = value;
            }

            /**
             * Gets the value of the precipMm property.
             * 
             */
            public float getPrecipMm() {
                return precipMm;
            }

            /**
             * Sets the value of the precipMm property.
             * 
             */
            public void setPrecipMm(float value) {
                this.precipMm = value;
            }

            /**
             * Gets the value of the cloudcover property.
             * 
             */
            public byte getCloudcover() {
                return cloudcover;
            }

            /**
             * Sets the value of the cloudcover property.
             * 
             */
            public void setCloudcover(byte value) {
                this.cloudcover = value;
            }

            /**
             * Gets the value of the humidity property.
             * 
             */
            public byte getHumidity() {
                return humidity;
            }

            /**
             * Sets the value of the humidity property.
             * 
             */
            public void setHumidity(byte value) {
                this.humidity = value;
            }

            /**
             * Gets the value of the visibilityKm property.
             * 
             */
            public byte getVisibilityKm() {
                return visibilityKm;
            }

            /**
             * Sets the value of the visibilityKm property.
             * 
             */
            public void setVisibilityKm(byte value) {
                this.visibilityKm = value;
            }

            /**
             * Gets the value of the pressureMb property.
             * 
             */
            public short getPressureMb() {
                return pressureMb;
            }

            /**
             * Sets the value of the pressureMb property.
             * 
             */
            public void setPressureMb(short value) {
                this.pressureMb = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="dir_degree" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="wind_unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "speed",
                "dir",
                "dirDegree",
                "windUnit"
            })
            public static class Wind {

                protected byte speed;
                @XmlElement(required = true)
                protected String dir;
                @XmlElement(name = "dir_degree")
                protected byte dirDegree;
                @XmlElement(name = "wind_unit", required = true)
                protected String windUnit;

                /**
                 * Gets the value of the speed property.
                 * 
                 */
                public byte getSpeed() {
                    return speed;
                }

                /**
                 * Sets the value of the speed property.
                 * 
                 */
                public void setSpeed(byte value) {
                    this.speed = value;
                }

                /**
                 * Gets the value of the dir property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDir() {
                    return dir;
                }

                /**
                 * Sets the value of the dir property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDir(String value) {
                    this.dir = value;
                }

                /**
                 * Gets the value of the dirDegree property.
                 * 
                 */
                public byte getDirDegree() {
                    return dirDegree;
                }

                /**
                 * Sets the value of the dirDegree property.
                 * 
                 */
                public void setDirDegree(byte value) {
                    this.dirDegree = value;
                }

                /**
                 * Gets the value of the windUnit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWindUnit() {
                    return windUnit;
                }

                /**
                 * Sets the value of the windUnit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWindUnit(String value) {
                    this.windUnit = value;
                }

            }

        }

    }


    public LiveWeather getCurrent_weather() {
    	// TODO Auto-generated method stub
    	LiveWeather liveWeather=new LiveWeather();
    	liveWeather.setHumidity(String.valueOf(currentWeather.getHumidity()));
    	liveWeather.setPressure(String.valueOf(currentWeather.getPressure()));
    	liveWeather.setTemp(String.valueOf(currentWeather.getTemp()));
    	com.airforecast.model.weather.Wind wind=new com.airforecast.model.weather.Wind(); liveWeather.setWind(wind);
    	wind.setSpeed(String.valueOf(currentWeather.getWind().getSpeed()));
    	wind.setDir(String.valueOf(currentWeather.getWind().getDir()));
    	return liveWeather;
    }
    public com.airforecast.model.weather.Forecast getFirstForecast(){
    	com.airforecast.model.weather.Day day=new com.airforecast.model.weather.Day();
    	com.airforecast.model.weather.Wind wind=new com.airforecast.model.weather.Wind();
    	com.airforecast.model.weather.Forecast  forcast=new com.airforecast.model.weather.Forecast();
    	if(forecast.size()>0){
    		forcast.setDay_max_temp(String.valueOf(forecast.get(0).dayMaxTemp));
    		day.setPressure_mb(String.valueOf(forecast.get(0).day.pressureMb));
    		wind.setDir(forecast.get(0).day.wind.dir);
    		wind.setSpeed(String.valueOf(forecast.get(0).day.wind.speed));
    		day.setWind(wind);forcast.setDay(day);
    	}
    	return forcast;
    }

}
