//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.01 at 08:24:40 AM IST 
//


package com.airforecast.model.weather;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.airforecast.model.weather package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.airforecast.model.weather
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Weather }
     * 
     */
    public Weather createWeather() {
        return new Weather();
    }

    /**
     * Create an instance of {@link Weather.Forecast }
     * 
     */
    public Weather.Forecast createWeatherForecast() {
        return new Weather.Forecast();
    }

    /**
     * Create an instance of {@link Weather.Forecast.Night }
     * 
     */
    public Weather.Forecast.Night createWeatherForecastNight() {
        return new Weather.Forecast.Night();
    }

    /**
     * Create an instance of {@link Weather.Forecast.Day }
     * 
     */
    public Weather.Forecast.Day createWeatherForecastDay() {
        return new Weather.Forecast.Day();
    }

    /**
     * Create an instance of {@link Weather.CurrentWeather }
     * 
     */
    public Weather.CurrentWeather createWeatherCurrentWeather() {
        return new Weather.CurrentWeather();
    }

    /**
     * Create an instance of {@link Weather.Forecast.Night.Wind }
     * 
     */
    public Weather.Forecast.Night.Wind createWeatherForecastNightWind() {
        return new Weather.Forecast.Night.Wind();
    }

    /**
     * Create an instance of {@link Weather.Forecast.Day.Wind }
     * 
     */
    public Weather.Forecast.Day.Wind createWeatherForecastDayWind() {
        return new Weather.Forecast.Day.Wind();
    }

    /**
     * Create an instance of {@link Weather.CurrentWeather.Wind }
     * 
     */
    public Weather.CurrentWeather.Wind createWeatherCurrentWeatherWind() {
        return new Weather.CurrentWeather.Wind();
    }

}
